<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\content\gnubg-data\*"
          CopyToOutputDirectory="PreserveNewest"
          LinkBase="gnubg-data"
          Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)..\content\gnubg-data\met\*"
          CopyToOutputDirectory="PreserveNewest"
          LinkBase="gnubg-data\met"
          Visible="false" />
  </ItemGroup>
</Project>
